### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by TomPed**
Any more caveats? or any FAQs?

### CODE REVIEW

**Comment by winklerjenn** [comment]
Skip to content
This repository
Search
Pull requests
Issues
Marketplace
Explore
 @winklerjenn
Sign out
6
12 17 codecov/example-bash
 Code  Pull requests 1  Insights
Comparing changes
Choose two branches to see what’s changed or to start a new pull request. If you need to, you can also .
  
There isn’t anything to compare.
master@{1525757692} and master are identical.

© 2018 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
API
Training
Shop
Blog
About
Press h to open a hovercard with more details.

**Review by DocOBITCOIN — APPROVED** [review]

**Comment by lJailani** [comment]
Theks

**Comment by lJailani** [comment]
Nice

**Comment by thomasrockhu** [comment]
Closing in favor of https://github.com/codecov/example-bash/pull/10

**Pull request closed without merging**
